# Generated by Django 4.2.3 on 2023-08-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanagerapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.TextField()),
                ('nssf_number', models.CharField(max_length=100)),
                ('nhif_number', models.CharField(max_length=100)),
                ('kra_pin', models.CharField(max_length=100)),
                ('nextofkin_first_name', models.CharField(max_length=100)),
                ('nextofkin_middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nextofkin_last_name', models.CharField(max_length=100)),
                ('nextofkin_country', models.CharField(max_length=100)),
                ('nextofkin_city', models.CharField(max_length=100)),
                ('nextofkin_address', models.CharField(max_length=100)),
                ('nextofkin_phone', models.CharField(max_length=100)),
                ('nextofkin_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanagerapp.company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanagerapp.department')),
            ],
        ),
    ]
