# Generated by Django 4.2.3 on 2023-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagerapp', '0002_company_website_alter_employee_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='state',
        ),
        migrations.RemoveField(
            model_name='company',
            name='zip',
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Enter company name'),
        ),
    ]
