# Generated by Django 4.2.3 on 2023-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagerapp', '0003_remove_company_state_remove_company_zip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Comapny'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(max_length=100, verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_address',
            field=models.CharField(max_length=100, verbose_name='Next of Kin Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_city',
            field=models.CharField(max_length=100, verbose_name='Next of Kin(s) City'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_country',
            field=models.CharField(max_length=100, verbose_name='Next of Kin(s) Country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_email',
            field=models.EmailField(max_length=100, verbose_name='Next of Kin(s) Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_first_name',
            field=models.CharField(max_length=100, verbose_name='Next of Kin First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_last_name',
            field=models.CharField(max_length=100, verbose_name='Next of Kin(s) Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin Middle Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nextofkin_phone',
            field=models.CharField(max_length=100, verbose_name='Next of Kin(s) Phone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nhif_number',
            field=models.CharField(max_length=100, verbose_name='NHIF Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(max_length=100, verbose_name='NSSF Number'),
        ),
    ]
