# Generated by Django 4.2.3 on 2023-08-04 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagerapp', '0004_alter_company_name_alter_department_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
    ]
