# Generated by Django 4.2.3 on 2023-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanagerapp', '0005_alter_company_options_alter_department_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
        migrations.AddField(
            model_name='department',
            name='company',
            field=models.ManyToManyField(to='hrmanagerapp.company'),
        ),
    ]
